server:
  port: 7001
spring:
  application:
    name: study-config-server
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chengwp/study-config.git
          username:
          password:
          clone-on-start: true
          search-paths:
            - study-config
    bus:
        refresh:
          enabled: true
management:
  endpoionts:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://192.168.101.3:8761/eureka/


