#设置端口号
server:
  port: 8888
eureka:
    instance:
      hostname: 192.168.101.3
    client:
      serviceUrl:
         defaultZone: http://192.168.101.3:8761/eureka
# DataSource Config
spring:
  application:
    name: study-provider
  hive: #hive数据源
    url: jdbc:hive2://192.168.101.9:10000/default
    type: com.alibaba.druid.pool.DruidDataSource
    username:
    password:
    driver-class-name: org.apache.hive.jdbc.HiveDriver
  commonconfig: #连接池统一配置，应用到所有的数据源
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 50
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 10000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      filters: stat
