#设置端口号
server:
  port: 8071

spring:
    application:
      name: study-provider

eureka:
    instance:
      hostname: 192.168.101.4
    client:
      service-url:
          default: http://192.168.101.4:8761/eureka/


