#设置端口号
server:
  port: 8071

spring:
    application:
      name: study-provide

eureka:
    instance:
      hostname: 192.168.101.4
    client:
      service-url:
          default: http://${eureka.instance.hostname}:8761/eureka/


