#设置端口号
server:
  port: 8888

spring:
    application:
      name: study-provider

eureka:
    instance:
      hostname: 192.168.101.4
    client:
      serviceUrl:
         defaultZone: http://192.168.101.4:8761/eureka


