spring:
  application:
    name: stud-api-gateway
#设置端口号
server:
    port: 9001
eureka:
  instance:
    hostname: 192.168.101.3
  client:
    serviceUrl:
      defaultZone: http://192.168.101.3:8761/eureka
zuul:
  routes:
     keys:
        path: /sc/**
        serviceId: study-consumer